// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/d2.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type M1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	M1            string                 `protobuf:"bytes,1,opt,name=m1,proto3" json:"m1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M1) Reset() {
	*x = M1{}
	mi := &file_proto_d2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M1) ProtoMessage() {}

func (x *M1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_d2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M1.ProtoReflect.Descriptor instead.
func (*M1) Descriptor() ([]byte, []int) {
	return file_proto_d2_proto_rawDescGZIP(), []int{0}
}

func (x *M1) GetM1() string {
	if x != nil {
		return x.M1
	}
	return ""
}

type M2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	M2            string                 `protobuf:"bytes,1,opt,name=m2,proto3" json:"m2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M2) Reset() {
	*x = M2{}
	mi := &file_proto_d2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2) ProtoMessage() {}

func (x *M2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_d2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2.ProtoReflect.Descriptor instead.
func (*M2) Descriptor() ([]byte, []int) {
	return file_proto_d2_proto_rawDescGZIP(), []int{1}
}

func (x *M2) GetM2() string {
	if x != nil {
		return x.M2
	}
	return ""
}

var File_proto_d2_proto protoreflect.FileDescriptor

const file_proto_d2_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/d2.proto\x12\x04p111\"\x14\n" +
	"\x02M1\x12\x0e\n" +
	"\x02m1\x18\x01 \x01(\tR\x02m1\"\x14\n" +
	"\x02M2\x12\x0e\n" +
	"\x02m2\x18\x01 \x01(\tR\x02m22\"\n" +
	"\x02S1\x12\x1c\n" +
	"\x04fun1\x12\b.p111.M1\x1a\b.p111.M2\"\x00B\rZ\vd1/proto;pbb\x06proto3"

var (
	file_proto_d2_proto_rawDescOnce sync.Once
	file_proto_d2_proto_rawDescData []byte
)

func file_proto_d2_proto_rawDescGZIP() []byte {
	file_proto_d2_proto_rawDescOnce.Do(func() {
		file_proto_d2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_d2_proto_rawDesc), len(file_proto_d2_proto_rawDesc)))
	})
	return file_proto_d2_proto_rawDescData
}

var file_proto_d2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_d2_proto_goTypes = []any{
	(*M1)(nil), // 0: p111.M1
	(*M2)(nil), // 1: p111.M2
}
var file_proto_d2_proto_depIdxs = []int32{
	0, // 0: p111.S1.fun1:input_type -> p111.M1
	1, // 1: p111.S1.fun1:output_type -> p111.M2
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_d2_proto_init() }
func file_proto_d2_proto_init() {
	if File_proto_d2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_d2_proto_rawDesc), len(file_proto_d2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_d2_proto_goTypes,
		DependencyIndexes: file_proto_d2_proto_depIdxs,
		MessageInfos:      file_proto_d2_proto_msgTypes,
	}.Build()
	File_proto_d2_proto = out.File
	file_proto_d2_proto_goTypes = nil
	file_proto_d2_proto_depIdxs = nil
}
