// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/d2.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	S1_Fun1_FullMethodName = "/p111.S1/fun1"
)

// S1Client is the client API for S1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type S1Client interface {
	Fun1(ctx context.Context, in *M1, opts ...grpc.CallOption) (*M2, error)
}

type s1Client struct {
	cc grpc.ClientConnInterface
}

func NewS1Client(cc grpc.ClientConnInterface) S1Client {
	return &s1Client{cc}
}

func (c *s1Client) Fun1(ctx context.Context, in *M1, opts ...grpc.CallOption) (*M2, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(M2)
	err := c.cc.Invoke(ctx, S1_Fun1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// S1Server is the server API for S1 service.
// All implementations must embed UnimplementedS1Server
// for forward compatibility.
type S1Server interface {
	Fun1(context.Context, *M1) (*M2, error)
	mustEmbedUnimplementedS1Server()
}

// UnimplementedS1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedS1Server struct{}

func (UnimplementedS1Server) Fun1(context.Context, *M1) (*M2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fun1 not implemented")
}
func (UnimplementedS1Server) mustEmbedUnimplementedS1Server() {}
func (UnimplementedS1Server) testEmbeddedByValue()            {}

// UnsafeS1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to S1Server will
// result in compilation errors.
type UnsafeS1Server interface {
	mustEmbedUnimplementedS1Server()
}

func RegisterS1Server(s grpc.ServiceRegistrar, srv S1Server) {
	// If the following call pancis, it indicates UnimplementedS1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&S1_ServiceDesc, srv)
}

func _S1_Fun1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(M1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S1Server).Fun1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S1_Fun1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S1Server).Fun1(ctx, req.(*M1))
	}
	return interceptor(ctx, in, info, handler)
}

// S1_ServiceDesc is the grpc.ServiceDesc for S1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var S1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "p111.S1",
	HandlerType: (*S1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "fun1",
			Handler:    _S1_Fun1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/d2.proto",
}
